services:
  - type: web
    name: lolz-otc-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        value: "8282073669"
